### PR TITLE
Added the option to download each game and DLC to their own folders.

### PR DESCRIPTION
**Pull request by Pixelformater**
Hi again, I reimplemented the option to download each game to their own separate folders. If you find anything that can be improved let me know.
Really like the icons you added btw.

### CODE REVIEW

**Comment by IcySon55** [comment]
Looks good. I actually wanted this feature as well. I'll push it forward to the main repo as well.

**Comment by IcySon55** [comment]
Oops, looks like your changes don't work for DLC.

I was thinking that since the DLC names are different from the game's name, using the name as the directory doesn't work so well. i think the TitleID would be a better choice.

**Comment by Pixelformater** [comment]
Hmm, I can't replicate the issue with normal unpacks when the directory checkbox isn't checked, although  haven't tried them on a vita, all the files seem to be there compared to when the checkbox is checked. Could you explain in more detail what the problem is?

Regarding the issue with DLC's names I was actually undecided on two approaches, so I left it as is.

The first approach I would put the DLC inside the main game's folder within a folder named after the DLC like this:
--->Root
       |---> Game XYZ
                |--->app
                |--->Game XYZ - Swimsuit Pack
                        |--->bgdl

This approach allows one to better archive DLCs but is more cumbersome when transfering them to the vita.

The second approach is unpacking them inside the game folder directly, using the the game folder as the root, like this:
--->Root
       |---> Game XYZ
                |--->app
                |--->bgdl 

I think this approach is better for transfering the dlcs to the vita, but obfuscates which DLCs you have a bit which, IMO, makes it harder for archiving DLCS.

I prefer the first approach but both can be implemented by creating another option for DLCs. I also have a pretty clear idea how to do do them both.

Assuming that the DLCs corresponding game is in the database it's possible to use the TitleName as the folder name, if not we should probably use the TitleID.

Hope to hear your opinion on this.

**Comment by IcySon55** [comment]
I think the issue with the implementation so far is that it's not accounting for the fact that pkg_dec actually accepts an output directory via the "pkg dec params" in the Options window.

I prefer the ready-to-copy approach and also to allow the user to define it via that output directory setting. Pesonally, I have these options set:

Download dir: ``.\NpS Browse\Games``
Params: ``--make-dirs=ux --license="{zRifKey}" [pkgFile} ..\``

The ``..\`` above means that the files will be extracted to ``.\NPS Browser``

What's missing is something like:
``--make-dirs=ux --license="{zRifKey}" [pkgFile} ..\{titleID}``

Which would extract everything to:
``.\NpS Browse\TitleID\addcont``
``.\NpS Browse\TitleID\app``
``.\NpS Browse\TitleID\license``

**Comment by Pixelformater** [comment]
Ok, I understand my mistake now, I wasn't accounting for the output directory being passed in the params for PkgDecrypt, as you said.

Regarding the extraction scenario that you mentioned, I was reading the [PkgDecrypt](https://github.com/weaknespase/PkgDecrypt/blob/master/README.md) documentation and noticed that we can replace the
`--make-dirs=ux` paramenter  with `--make-dirs=id` and would obtain something close to what you mentioned.

This parameter extracts to a folder similar to the this:

`.\NpS Browse\TitleID_randomNumbers\*`

My idea is the following:

Download dir: `.\NpS Browse\Games\`
Params `--make-dirs=id --license="{zRifKey}" {pkgFile}`

If the option to download to a folder named after TitleID was checked, the application flow would be something like this:

Download path for the pkg: `.\NpS Browse\Games\TitleID\app\TitleID.pkg`

After the unpack: `.\NpS Browse\Games\TitleID\app\TitleID_randomNumbers\*`

Rename the `TitleID_randomNumbers` to simply `TitleId` and the following file directory structure would result: `.\NpS Browse\Games\TitleID\app\TitleID\*`

For the DLC structure a new field inside `Item` class would have to be created to distinguish what is a DLC and what isn't, the process would be similar to he described above:

Download path for the pkg: `.\NpS Browse\Games\TitleID\addcont\TitleID.pkg`

After the unpack: `.\NpS Browse\Games\TitleID\addcont\TitleID_dlcNumber_DLCName\*`

Rename the `TitleID_dlcNumber_DLCName` to simply `TitleId` and the following file directory structure would result: `.\NpS Browse\Games\TitleID\addcont\TitleID\*`

About the `license` folder I'm not very knowledgable about the DLC extraction process but I assume that the `work.bin` inside the DLC folder is still the zrif license, if so we would only have to create a folder named licence and after the DLC is unpacked we would have to copy/move the work.bin from the DLC folder and rename it ``{zRif}.zrif`.

Unfortunately this would only further break the option to pass an output folder in "pkg dec params" and would also restrict the possibility to modify the ``--make-dirs=` parameter.

**Comment by IcySon55** [comment]
``pkg_dec.exe`` already creates the ``license`` directories along with the ``addcont`` directories when using ``--make-dirs=ux``.

So really, all we need to do is to add support for ``{titleID}`` in the params field.

**Pull request merged**
